FROM python:3.7.4-buster

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip && pip install -r requirements.txt

RUN pip install uwsgi

RUN apt-get update && apt-get install -y --no-install-recommends \
    vim

CMD ["uwsgi", "uwsgi.ini"]

